- ros_topic_name: "unilidar/pointcloud"
  gz_topic_name: "/unilidar/pointcloud"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

