- ros_topic_name: "/lidar"
  gz_topic_name: "/unilidar/pointcloud/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked" # ign topic -i -t /unilidar/pointcloud/points
  direction: GZ_TO_ROS
